### PR TITLE
Add Version to Manifest

### PR DESCRIPTION
**Pull request by GuyKh**
Solves Issue #65

### CODE REVIEW

**Comment by ludeeus** [comment]
This will require an update of that key for each version, which's not maintainable for me.
Something like <https://github.com/hacs/integration/blob/main/.github/workflows/release.yml> needs to be added, but I understand that is too much to ask.
I will do that eventually if no one beats me to it.

**Comment by GuyKh** [comment]
@ludeeus 
I took the liberty to beat you to it :)

**Comment by ludeeus** [comment]
Can you use this instead? <https://github.com/custom-components/breaking_changes/blob/main/.github/workflows/release.yaml>

**Comment by GuyKh** [comment]
@ludeeus 
Done.
Now need to try this :)

**Review by ludeeus — APPROVED** [review]

**Comment by ludeeus** [comment]
I've used that exact file in 2 other repos, so should not be an issue

**Comment by GuyKh** [comment]
Strangely, upon merge, the action didn't run

**Comment by ludeeus** [comment]
It's not supposed to, it's run when a release is released

**Comment by ludeeus** [comment]
https://github.com/custom-components/authenticated/runs/2047537506?check_suite_focus=true

**Comment by GuyKh** [comment]
Ahhhhh. Good to know!

**Pull request merged**
